workflows:
    acme_demo_workflow_lead_processing:
        label:      'Lead Processing Flow'
        entity:     OroCRM\Bundle\SalesBundle\Entity\Lead
        start_step: open
        steps_display_ordered: true
        steps:
            open:
                label: 'Open'
                order: 10
                allowed_transitions:
                    - start_progress
            in_progress:
                label: 'In progress'
                order: 20
                allowed_transitions:
                    - close
            closed:
                label: 'Closed'
                order: 30
                allowed_transitions:
                    - reopen

        transitions:
            start_progress:
                label:        'Start progress'
                step_to:      in_progress
                transition_definition: start_progress_definition
            close:
                label:        'Close'
                step_to:      closed
                transition_definition: close_definition
            reopen:
                label:        'Reopen'
                step_to:      open
                transition_definition: reopen_definition

        transition_definitions:
            start_progress_definition: ~
            close_definition: ~
            reopen_definition: ~
